In [60]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
from sklearn.model_selection import train_test_split

In [61]:
# load dataset(train and test)
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [62]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [63]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

# Using the info() to observer whether the dataset have missing value

In [64]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
FireplaceQu      770 non-null object
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
PoolQC           7 non-null object
Fence            281 non-null object
MiscFeature      54 non-null object
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [65]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
Id               1459 non-null int64
MSSubClass       1459 non-null int64
MSZoning         1455 non-null object
LotFrontage      1232 non-null float64
LotArea          1459 non-null int64
Street           1459 non-null object
Alley            107 non-null object
LotShape         1459 non-null object
LandContour      1459 non-null object
Utilities        1457 non-null object
LotConfig        1459 non-null object
LandSlope        1459 non-null object
Neighborhood     1459 non-null object
Condition1       1459 non-null object
Condition2       1459 non-null object
BldgType         1459 non-null object
HouseStyle       1459 non-null object
OverallQual      1459 non-null int64
OverallCond      1459 non-null int64
YearBuilt        1459 non-null int64
YearRemodAdd     1459 non-null int64
RoofStyle        1459 non-null object
RoofMatl         1459 non-null object
Exterior1st      1458 non-null object
Exterior2nd      1458 non-null object
MasVnrType       1443 non-null object
MasVnrArea       1444 non-null float64
ExterQual        1459 non-null object
ExterCond        1459 non-null object
Foundation       1459 non-null object
BsmtQual         1415 non-null object
BsmtCond         1414 non-null object
BsmtExposure     1415 non-null object
BsmtFinType1     1417 non-null object
BsmtFinSF1       1458 non-null float64
BsmtFinType2     1417 non-null object
BsmtFinSF2       1458 non-null float64
BsmtUnfSF        1458 non-null float64
TotalBsmtSF      1458 non-null float64
Heating          1459 non-null object
HeatingQC        1459 non-null object
CentralAir       1459 non-null object
Electrical       1459 non-null object
1stFlrSF         1459 non-null int64
2ndFlrSF         1459 non-null int64
LowQualFinSF     1459 non-null int64
GrLivArea        1459 non-null int64
BsmtFullBath     1457 non-null float64
BsmtHalfBath     1457 non-null float64
FullBath         1459 non-null int64
HalfBath         1459 non-null int64
BedroomAbvGr     1459 non-null int64
KitchenAbvGr     1459 non-null int64
KitchenQual      1458 non-null object
TotRmsAbvGrd     1459 non-null int64
Functional       1457 non-null object
Fireplaces       1459 non-null int64
FireplaceQu      729 non-null object
GarageType       1383 non-null object
GarageYrBlt      1381 non-null float64
GarageFinish     1381 non-null object
GarageCars       1458 non-null float64
GarageArea       1458 non-null float64
GarageQual       1381 non-null object
GarageCond       1381 non-null object
PavedDrive       1459 non-null object
WoodDeckSF       1459 non-null int64
OpenPorchSF      1459 non-null int64
EnclosedPorch    1459 non-null int64
3SsnPorch        1459 non-null int64
ScreenPorch      1459 non-null int64
PoolArea         1459 non-null int64
PoolQC           3 non-null object
Fence            290 non-null object
MiscFeature      51 non-null object
MiscVal          1459 non-null int64
MoSold           1459 non-null int64
YrSold           1459 non-null int64
SaleType         1458 non-null object
SaleCondition    1459 non-null object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [66]:
train.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [67]:
test.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
count,1459.000000,1459.000000,1232.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1444.000000,1458.000000,...,1458.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000
mean,2190.000000,57.378341,68.580357,9819.161069,6.078821,5.553804,1971.357779,1983.662783,100.709141,439.203704,...,472.768861,93.174777,48.313914,24.243317,1.794380,17.064428,1.744345,58.167923,6.104181,2007.769705
std,421.321334,42.746880,22.376841,4955.517327,1.436812,1.113740,30.390071,21.130467,177.625900,455.268042,...,217.048611,127.744882,68.883364,67.227765,20.207842,56.609763,30.491646,630.806978,2.722432,1.301740
min,1461.000000,20.000000,21.000000,1470.000000,1.000000,1.000000,1879.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000
25%,1825.500000,20.000000,58.000000,7391.000000,5.000000,5.000000,1953.000000,1963.000000,0.000000,0.000000,...,318.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000
50%,2190.000000,50.000000,67.000000,9399.000000,6.000000,5.000000,1973.000000,1992.000000,0.000000,350.500000,...,480.000000,0.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000
75%,2554.500000,70.000000,80.000000,11517.500000,7.000000,6.000000,2001.000000,2004.000000,164.000000,753.500000,...,576.000000,168.000000,72.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000
max,2919.000000,190.000000,200.000000,56600.000000,10.000000,9.000000,2010.000000,2010.000000,1290.000000,4010.000000,...,1488.000000,1424.000000,742.000000,1012.000000,360.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000

In [74]:
# feature we want to keep and analysis
features = ['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'LotShape', 'LotShape', 'Utilities', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtFinSF1', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', '1stFlrSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'FireplaceQu', 'GarageCars', 'GarageArea', 'GarageQual', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice']

In [75]:
# append train and test set for data preprocessing
datas = train.append(test)
datas.reset_index(inplace=True, drop=True)

In [76]:
# filte the some specific we want
datas = datas[features]

In [77]:
datas

,MSSubClass,MSZoning,LotFrontage,LotArea,LotShape,LotShape,Utilities,OverallQual,OverallCond,YearBuilt,...,TotRmsAbvGrd,Fireplaces,FireplaceQu,GarageCars,GarageArea,GarageQual,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Reg,Reg,AllPub,7,5,2003,...,8,0,NaN,2.0,548.0,TA,2008,WD,Normal,208500.0
1,20,RL,80.0,9600,Reg,Reg,AllPub,6,8,1976,...,6,1,TA,2.0,460.0,TA,2007,WD,Normal,181500.0
2,60,RL,68.0,11250,IR1,IR1,AllPub,7,5,2001,...,6,1,TA,2.0,608.0,TA,2008,WD,Normal,223500.0
3,70,RL,60.0,9550,IR1,IR1,AllPub,7,5,1915,...,7,1,Gd,3.0,642.0,TA,2006,WD,Abnorml,140000.0
4,60,RL,84.0,14260,IR1,IR1,AllPub,8,5,2000,...,9,1,TA,3.0,836.0,TA,2008,WD,Normal,250000.0
5,50,RL,85.0,14115,IR1,IR1,AllPub,5,5,1993,...,5,0,NaN,2.0,480.0,TA,2009,WD,Normal,143000.0
6,20,RL,75.0,10084,Reg,Reg,AllPub,8,5,2004,...,7,1,Gd,2.0,636.0,TA,2007,WD,Normal,307000.0
7,60,RL,NaN,10382,IR1,IR1,AllPub,7,6,1973,...,7,2,TA,2.0,484.0,TA,2009,WD,Normal,200000.0
8,50,RM,51.0,6120,Reg,Reg,AllPub,7,5,1931,...,8,2,TA,2.0,468.0,Fa,2008,WD,Abnorml,129900.0
9,190,RL,50.0,7420,Reg,Reg,AllPub,5,6,1939,...,5,2,TA,1.0,205.0,Gd,2008,WD,Normal,118000.0
10,20,RL,70.0,11200,Reg,Reg,AllPub,5,5,1965,...,5,0,NaN,1.0,384.0,TA,2008,WD,Normal,129500.0
11,60,RL,85.0,11924,IR1,IR1,AllPub,9,5,2005,...,11,2,Gd,3.0,736.0,TA,2006,New,Partial,345000.0
12,20,RL,NaN,12968,IR2,IR2,AllPub,5,6,1962,...,4,0,NaN,1.0,352.0,TA,2008,WD,Normal,144000.0
13,20,RL,91.0,10652,IR1,IR1,AllPub,7,5,2006,...,7,1,Gd,3.0,840.0,TA,2007,New,Partial,279500.0
14,20,RL,NaN,10920,IR1,IR1,AllPub,6,5,1960,...,5,1,Fa,1.0,352.0,TA,2008,WD,Normal,157000.0
15,45,RM,51.0,6120,Reg,Reg,AllPub,7,8,1929,...,5,0,NaN,2.0,576.0,TA,2007,WD,Normal,132000.0
16,20,RL,NaN,11241,IR1,IR1,AllPub,6,7,1970,...,5,1,TA,2.0,480.0,TA,2010,WD,Normal,149000.0
17,90,RL,72.0,10791,Reg,Reg,AllPub,4,5,1967,...,6,0,NaN,2.0,516.0,TA,2006,WD,Normal,90000.0
18,20,RL,66.0,13695,Reg,Reg,AllPub,5,5,2004,...,6,0,NaN,2.0,576.0,TA,2008,WD,Normal,159000.0
19,20,RL,70.0,7560,Reg,Reg,AllPub,5,6,1958,...,6,0,NaN,1.0,294.0,TA,2009,COD,Abnorml,139000.0
20,60,RL,101.0,14215,IR1,IR1,AllPub,8,5,2005,...,9,1,Gd,3.0,853.0,TA,2006,New,Partial,325300.0
21,45,RM,57.0,7449,Reg,Reg,AllPub,7,7,1930,...,6,1,Gd,1.0,280.0,TA,2007,WD,Normal,139400.0
22,20,RL,75.0,9742,Reg,Reg,AllPub,8,5,2002,...,7,1,Gd,2.0,534.0,TA,2008,WD,Normal,230000.0
23,120,RM,44.0,4224,Reg,Reg,AllPub,5,7,1976,...,6,1,TA,2.0,572.0,TA,2007,WD,Normal,129900.0
24,20,RL,NaN,8246,IR1,IR1,AllPub,5,8,1968,...,6,1,TA,1.0,270.0,TA,2010,WD,Normal,154000.0
25,20,RL,110.0,14230,Reg,Reg,AllPub,8,5,2007,...,7,1,Gd,3.0,890.0,TA,2009,WD,Normal,256300.0
26,20,RL,60.0,7200,Reg,Reg,AllPub,5,7,1951,...,5,0,NaN,2.0,576.0,TA,2010,WD,Normal,134800.0
27,20,RL,98.0,11478,Reg,Reg,AllPub,8,5,2007,...,7,1,Gd,3.0,772.0,TA,2010,WD,Normal,306000.0
28,20,RL,47.0,16321,IR1,IR1,AllPub,5,6,1957,...,6,2,Gd,1.0,319.0,TA,2006,WD,Normal,207500.0
29,30,RM,60.0,6324,IR1,IR1,AllPub,4,6,1927,...,4,0,NaN,1.0,240.0,Fa,2008,WD,Normal,68500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2889,30,RM,50.0,7030,Reg,Reg,AllPub,4,6,1925,...,4,0,NaN,1.0,272.0,TA,2006,WD,Normal,NaN
2890,50,RM,75.0,9060,Reg,Reg,AllPub,6,5,1957,...,6,0,NaN,1.0,384.0,TA,2006,WD,Normal,NaN
2891,30,C (all),69.0,12366,Reg,Reg,AllPub,3,5,1945,...,5,0,NaN,0.0,0.0,NaN,2006,WD,Abnorml,NaN
2892,190,C (all),50.0,9000,Reg,Reg,AllPub,5,6,1951,...,8,0,NaN,0.0,0.0,NaN,2006,WD,Abnorml,NaN
2893,50,C (all),60.0,8520,Reg,Reg,AllPub,3,5,1916,...,6,0,NaN,0.0,0.0,NaN,2006,WD,Normal,NaN
2894,120,RM,41.0,5748,IR1,IR1,AllPub,8,5,2005,...,5,1,Gd,2.0,495.0,TA,2006,New,Partial,NaN
2895,120,RM,44.0,3842,IR1,IR1,AllPub,8,5,2004,...,5,1,Gd,2.0,525.0,TA,2006,WD,Normal,NaN
2896,20,RL,69.0,23580,IR1,IR1,AllPub,6,6,1979,...,6,1,TA,2.0,576.0,TA,2006,WD,Normal,NaN
2897,90,RL,65.0,8385,Reg,Reg,AllPub,6,5,1978,...,10,0,NaN,2.0,616.0,TA,2006,WD,Normal,NaN
2898,20,RL,70.0,9116,Reg,Reg,AllPub,8,5,2001,...,7,0,NaN,2.0,490.0,TA,2006,WD,Normal,NaN
2899,80,RL,140.0,11080,Reg,Reg,AllPub,6,6,1975,...,6,0,NaN,2.0,528.0,TA,2006,WD,Normal,NaN
2900,20,RL,NaN,50102,IR1,IR1,AllPub,6,5,1958,...,6,2,Gd,2.0,518.0,TA,2006,WD,Alloca,NaN
2901,20,RL,NaN,8098,IR1,IR1,AllPub,6,5,2000,...,5,0,NaN,2.0,470.0,TA,2006,WD,Normal,NaN
2902,20,RL,95.0,13618,Reg,Reg,AllPub,8,5,2005,...,8,2,Gd,3.0,714.0,TA,2006,New,Partial,NaN
2903,20,RL,88.0,11577,Reg,Reg,AllPub,9,5,2005,...,9,1,Gd,3.0,682.0,TA,2006,New,Partial,NaN
2904,20,NaN,125.0,31250,Reg,Reg,AllPub,1,3,1951,...,6,0,NaN,1.0,270.0,Fa,2006,WD,Normal,NaN
2905,90,RM,78.0,7020,Reg,Reg,AllPub,7,5,1997,...,8,0,NaN,4.0,784.0,TA,2006,WD,Normal,NaN
2906,160,RM,41.0,2665,Reg,Reg,AllPub,5,6,1977,...,5,1,TA,1.0,336.0,TA,2006,WD,Normal,NaN
2907,20,RL,58.0,10172,IR1,IR1,AllPub,5,7,1968,...,5,0,NaN,1.0,288.0,TA,2006,WD,Normal,NaN
2908,90,RL,NaN,11836,IR1,IR1,AllPub,5,5,1970,...,8,0,NaN,3.0,928.0,TA,2006,WD,Normal,NaN
2909,180,RM,21.0,1470,Reg,Reg,AllPub,4,6,1970,...,3,0,NaN,0.0,0.0,NaN,2006,WD,Normal,NaN
2910,160,RM,21.0,1484,Reg,Reg,AllPub,4,4,1972,...,5,0,NaN,1.0,253.0,TA,2006,WD,Normal,NaN
2911,20,RL,80.0,13384,Reg,Reg,AllPub,5,5,1969,...,8,1,TA,1.0,336.0,TA,2006,WD,Normal,NaN
2912,160,RM,21.0,1533,Reg,Reg,AllPub,4,5,1970,...,5,0,NaN,1.0,286.0,TA,2006,WD,Abnorml,NaN
2913,160,RM,21.0,1526,Reg,Reg,AllPub,4,5,1970,...,5,0,NaN,0.0,0.0,NaN,2006,WD,Normal,NaN
2914,160,RM,21.0,1936,Reg,Reg,AllPub,4,7,1970,...,5,0,NaN,0.0,0.0,NaN,2006,WD,Normal,NaN
2915,160,RM,21.0,1894,Reg,Reg,AllPub,4,5,1970,...,6,0,NaN,1.0,286.0,TA,2006,WD,Abnorml,NaN
2916,20,RL,160.0,20000,Reg,Reg,AllPub,5,7,1960,...,7,1,TA,2.0,576.0,TA,2006,WD,Abnorml,NaN
2917,85,RL,62.0,10441,Reg,Reg,AllPub,5,5,1992,...,6,0,NaN,0.0,0.0,NaN,2006,WD,Normal,NaN
2918,60,RL,74.0,9627,Reg,Reg,AllPub,7,5,1993,...,9,1,TA,3.0,650.0,TA,2006,WD,Normal,NaN

In [83]:
datas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 44 columns):
MSSubClass       2919 non-null object
MSZoning         2919 non-null object
LotFrontage      2434 non-null object
LotArea          2919 non-null object
LotShape         2919 non-null object
LotShape         2919 non-null object
Utilities        2918 non-null object
OverallQual      2919 non-null object
OverallCond      2919 non-null object
YearBuilt        2919 non-null object
YearRemodAdd     2919 non-null object
RoofStyle        2919 non-null object
RoofMatl         2919 non-null object
Exterior1st      2918 non-null object
Exterior2nd      2918 non-null object
MasVnrType       2895 non-null object
MasVnrArea       2896 non-null object
ExterQual        2919 non-null object
ExterCond        2919 non-null object
Foundation       2919 non-null object
BsmtQual         2841 non-null object
BsmtFinSF1       2918 non-null object
TotalBsmtSF      2918 non-null object
Heating          2919 non-null object
HeatingQC        2919 non-null object
CentralAir       2919 non-null object
1stFlrSF         2919 non-null object
GrLivArea        2919 non-null object
BsmtFullBath     2917 non-null object
BsmtHalfBath     2917 non-null object
FullBath         2919 non-null object
HalfBath         2919 non-null object
BedroomAbvGr     2919 non-null object
KitchenAbvGr     2919 non-null object
TotRmsAbvGrd     2919 non-null object
Fireplaces       2919 non-null object
FireplaceQu      1503 non-null object
GarageCars       2918 non-null object
GarageArea       2918 non-null object
GarageQual       2760 non-null object
YrSold           2919 non-null object
SaleType         2918 non-null object
SaleCondition    2919 non-null object
SalePrice        1464 non-null object
dtypes: object(44)
memory usage: 1003.5+ KB

In [86]:
# fill the MSZoning with frequency occur

datas[datas['LotFrontage'].isnull()] =

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [105]:
datas[~datas['LotFrontage'].isnull()]['LotFrontage'].astype

<bound method NDFrame.astype of 0        65
1        80
2        68
3        60
4        84
5        85
6        75
8        51
9        50
10       70
11       85
13       91
15       51
17       72
18       66
19       70
20      101
21       57
22       75
23       44
25      110
26       60
27       98
28       47
29       60
30       50
32       85
33       70
34       60
35      108
       ...
2886     50
2887     50
2888     61
2889     50
2890     75
2891     69
2892     50
2893     60
2894     41
2895     44
2896     69
2897     65
2898     70
2899    140
2902     95
2903     88
2904     RL
2905     78
2906     41
2907     58
2909     21
2910     21
2911     80
2912     21
2913     21
2914     21
2915     21
2916    160
2917     62
2918     74
Name: LotFrontage, Length: 2434, dtype: object>